enable-module-update = true 
parallel-jobs = 1
remove-rv-integrations-checks = false

cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"


["YouTube-Extended-19.43.41"]
app-name = "YouTube"
pkg-name = "com.google.android.youtube"
rv-brand = "ReVanced Extended"
module-prop-name = "youtube-extended-19-43-41"
build-mode = "both"
version = "19.43.41"
patches-source = "anddea/revanced-patches"
patches-version = "v4.3.0-dev.6"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/revanced-extended-stock-apks/"

["YouTube-Extended-19.28.42"]
app-name = "YouTube"
pkg-name = "com.google.android.youtube"
rv-brand = "ReVanced Extended"
module-prop-name = "youtube-extended-19-28-42"
build-mode = "both"
version = "19.28.42"
patches-source = "anddea/revanced-patches"
patches-version = "v4.3.0-dev.6"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/revanced-extended-stock-apks/"
